apiVersion: batch/v1
kind: Job
metadata:
  name: curator-job
  namespace: elk
spec:
  template:
    spec:
      containers:
      - name: curator-job
        image: bobrik/curator:5.6.0
        command: ["curator",  "--config", "/etc/config/config.yml", "/etc/config/action_file.yml"]
        volumeMounts:
          - name: config-volume
            mountPath: /etc/config
      restartPolicy: OnFailure
      volumes:
        - name: config-volume
          configMap:
            name: curator-config