---
apiVersion: v1
kind: Service
metadata:
  labels:
    component: logstash
  namespace: elk
  name: logstash-lb
spec:
  selector:
    component: logstash
  ports:
  - name: lumberjack
    port: 5043
    targetPort: 5043
    protocol: TCP
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  labels:
    component: logstash
  namespace: elk
  name: logstash-api
spec:
  selector:
    component: logstash
  ports:
  - name: logstash-api
    port: 9600
    targetPort: 9600
    protocol: TCP
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: logstash
  namespace: elk
  labels:
    component: logstash
spec:
  replicas: 2
  template:
    metadata:
      labels:
        component: logstash
    spec:
      serviceAccount: logstash
      containers:
      - name: logstash
        image: docker.elastic.co/logstash/logstash:6.6.1
        env:
        - name: KUBERNETES_TRUST_CERT
          value: "false"
        ports:
        - containerPort: 5043
          name: lumberjack
          protocol: TCP
        volumeMounts:
        - mountPath: /certs
          name: certs
        - name: logstash-indexer
          mountPath: /usr/share/logstash/pipeline/indexer.conf
          subPath: indexer.conf
      volumes:
      - emptyDir:
          medium: ""
        name: "storage"
      - hostPath:
          path: "/tmp"
        name: "certs"
      - name: logstash-indexer
        configMap:
          name: logstash-indexer
          items:
            - key: indexer.conf
              path: indexer.conf
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: logstash