---
apiVersion: v1
kind: Service
metadata:
  name: redis-indexer
  namespace: elk
  labels:
    app: redis
spec:
  type: NodePort
  selector:
    app: redis
  ports:
  - name: redis-port
    port: 6379
    targetPort: 6379
    protocol: TCP
  externalIPs:
  - 1.2.3.4  #The external IP address to allow connections for redis
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: redis
  name: redis
  namespace: elk
spec:
  containers:
  - name: redis
    image: redis:5-alpine
    env:
    - name: MASTER
      value: "true"
    ports:
    - containerPort: 6379
    resources:
      limits:
        cpu: "0.1"
        memory: 1G  #For production server can be increased
    volumeMounts:
    - mountPath: /redis-master-data
      name: data
    - mountPath: /redis-master
      name: config
  volumes:
    - name: data
      emptyDir: {}
    - name: config
      configMap:
        name: redis-config
        items:
        - key: redis-config
          path: redis.conf
