apiVersion: v1
kind: ConfigMap
metadata:
  namespace: elk
  name: role-mapping
  labels:
    app: elasticsearch
data:
  role_mapping.yml: |
    monitoring:
      - "cn=admins,dc=example,dc=local"
      - "cn=users,dc=example,dc=local"
    user:
      - "cn=users,dc=example,dc=local"
      - "cn=admins,dc=example,dc=local"
